### ISSUE TITLE
Revisar mobile version. 

### ISSUE THREAD

**Issue by ShankyJS** [adielhercules/aguinaldosv#4]
Hay que revisar la versión mobile, debido que para ver todo el contenido es necesario desplazarse a la derecha.

![Screenshot from 2019-10-30 11-08-15](https://user-images.githubusercontent.com/17713708/67881242-c16c0180-fb05-11e9-8c99-bed40171cc48.png)

**Comment by adielhercules** [comment]
Arreglado en PR #15
