### ISSUE TITLE
Cambiar label "Tiempo en la empresa" por algo más descriptivo

### ISSUE THREAD

**Issue by moudev** [adielhercules/aguinaldosv#5]
Me resultó confuso el label de "Tiempo en la empresa", a primera impresión pensé que el campo trataba que se tiene que digitar un número de meses, pero se abre un calendario, a lo mejor resultaría más entendible algo como "Inicio de contrato", eso me da a entender que el campo trata de ingresar un fecha.

***
Edit: Lo siento, no había notado que ya estaba el issue #3 , que trata sobre lo mismo.

**Comment by adielhercules** [comment]
Hola @moudev gracias por reportar el problema, correcto, ya ha sido reportado el problema en el issue #3, de igual forma mantedremos abierto este issue y lo cerramos al completar ese cambio gracias!

**Comment by adielhercules** [comment]
El PR #7 soluciona este problema. Cerrando hilo
